version: '3.8'

services:
  app_service:
    build:
      context: ./app
      dockerfile: Dockerfile
    container_name: app_service
    restart: always
    ports:
      - "8000:8000"  # 필요 시 포트 매핑

  scheduled:
    build:
      context: ./scheduled
      dockerfile: Dockerfile
    container_name: scheduled_service
    restart: always