name: Deploy to EC2

on:
  workflow_run:
    workflows: ["Build and Push to ECR"]  # 빌드 워크플로우의 이름
    types:
        - completed 

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}
      
      - name: Login to ECR
        run: |
          aws ecr get-login-password --region ${{ secrets.AWS_REGION }} | docker login --username AWS --password-stdin ${{ secrets.AWS_ACCOUNT }}.dkr.ecr.${{ secrets.AWS_REGION }}.amazonaws.com
        continue-on-error: false
      
      - name: Pull Docker image from ECR
        run: |
          docker pull ${{ secrets.AWS_ACCOUNT }}.dkr.ecr.${{ secrets.AWS_REGION }}.amazonaws.com/eunsung-ecr:latest
        continue-on-error: false
      
      - name: Deploy to EC2
        run: |
          ssh -o StrictHostKeyChecking=no real-estate-newsletter-admin@52.78.17.127 "docker-compose pull && docker-compose up -d --remove-orphans"